ubioworo:
  outputs:
    dev:
      account: 
      database: snowflake_dbt
      password: 
      role: my_snowflake_role
      schema: snowflake_mart_schema
      threads: 6
      type: snowflake
      user: ubio
      warehouse: my_snowflake_dbt_warehouse
  target: dev
